language: python
python:
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/conda

before_install:
  - bash deps/travis-install-conda.sh
  - export PATH="$HOME/conda/bin:$PATH"
  - source activate "test-environment-${TRAVIS_PYTHON_VERSION}"

install:
  - pip install .

script:
  - pytest

after_success:
  - coveralls
  - codeclimate-test-reporter
  - codecov
